### ISSUE TITLE
The dot ensime

### ISSUE THREAD

**Issue by dcsobral** [djspiewak/ensime-sidekick#1]
You should really document on the readme what goes inside .ensime. Maybe it ought to be obvious, but I didn't see it neither in ensime-sidekick, nor on ensime itself.

**Comment by djspiewak** [comment]
http://aemon.com/file_dump/ensime_manual.html#tth_sEc3.3

Not the clearest documentation in the world, but it does exist!

In general, all you should need is something like this:

```
(:use-sbt t)
```
