### ISSUE TITLE
Initialization failed with Java.util.NoSuchElementException: key not found: :subprojects

### ISSUE THREAD

**Issue by benqua** [djspiewak/ensime-sidekick#14]
Hello,

with the following .ensime:
(

:project-package "org.test"

:use-sbt t

)

a "Java.util.NoSuchElementException: key not found: :subprojects" exception is thrown, coming from  src/main/scala/com/codecommit/es/EnsimePlugin.scala, line 91.

Is it mandatory to define :subprojects? And :name or :ensime.home?

ben

**Comment by djspiewak** [comment]
ENSIME no longer supports .ensime files in that format.  You need to use the ensime generator plugin for SBT.  http://aemon.com/file_dump/ensime_manual.html#tth_sEc3.1
