### ISSUE TITLE
port of recent ensime-emacs changes

### ISSUE THREAD

**Issue by fommil** [djspiewak/ensime-sidekick#15]
there has been something of a revival in ENSIME recently. It would be great to see this project come back to life :-)

If you do decide to work on this again, you're more than welcome to join the ensime organisation and move this client into that organisation for increased exposure.

**Comment by djspiewak** [comment]
I'll need to take a look at the recent work when I get the chance.  I haven't been using ENSIME at all of late because of the bugs in the presentation compiler w.r.t. path dependent types.  If that case is working now (or at least not causing spurious errors), I would get a lot of value out of reactivating ensime in my editor.

**Comment by fommil** [comment]
We can't really speak for the presentation compiler but I understand things have come along.

There haven't been an awful lot of changes in functionality to ENSIME recently, but we have gone through a big upgrade to continuous integration and automatic deployments which dramatically lowers the barrier of entry for contributors. There are also a few of us who are now creating plans to add real features over the coming weeks and months (plus we're trying to encourage contributions with bountysource).

**Comment by fommil** [comment]
actually, if its been three years, there might have been quite a few new things.

More recently we added support for parsing of source jars so that "go to definition" queries can effectively go to source code of anything on the classpath (assuming its OSS).

**Comment by fommil** [comment]
btw, you should be able to have a scala client with the latest snapshots. All the messages can now be marshalled and received via the spray-json style S-Express library. More at scala days :wink:
