### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by vdichev** [djspiewak/ensime-sidekick#4]
When initializing ensime, there remain thousands (in the order of 6k-7k+ on my machine) of open files to the same file, /tmp/ensimeNNNN.port.

The bug seems to be in BackendComponent.scala:

while (port < 0) {
  val src = Source fromFile portFile
  src.getLines map { _.toInt } foreach { port = _ }
}

This needs src.close at the end of the loop.

**Comment by djspiewak** [comment]
Silly mistake on my part.  Fixed!
