### ISSUE TITLE
Ensime doesn't start

### ISSUE THREAD

**Issue by vdichev** [djspiewak/ensime-sidekick#5]
Ensime fails to initialize with no error messages.

After debugging the problem was discovered to be in the freshly generated .ensime file, which contained a comment. However, the following error message in EnsimePlugin.scala doesn't pop up at all:

"Project file is invalid.  Make sure it consists of a single s-expression.  (no comments!)"

It would be really helpful if either the comment in the s-expression is ignored, or at least the error message is shown, so the user doesn't have to look through the source to find out what the problem is ;-)

**Comment by djspiewak** [comment]
I was testing on the wrong return result for `SExp.read`.  Fixed now!

Ideally, we would just add support for parsing ELisp comments to `SExp`.  If someone wants to take on that task, that would be fantastic!
