### ISSUE TITLE
File open from symlinked dir is ignored

### ISSUE THREAD

**Issue by vdichev** [djspiewak/ensime-sidekick#6]
Files open with a different path than the canonical one are not processed and type-checked. E.g. if /media/Work is a symlink to /mnt/sda8, then /media/Work/Develop/somefile doesn't work, whereas /mnt/sda8/Develop/somefile works.

Probably related: path to ".ensime" file gets canonicalized.

**Comment by djspiewak** [comment]
Actually, it's due to the fact that the file paths are canonicalized.  I should probably just use `getAbsolutePath` instead.

**Comment by djspiewak** [comment]
Fixed in the most recent build.
